### ISSUE TITLE
Problem with no value for "PartnercenterEndpoint"

### ISSUE THREAD

**Issue by martinliljenberg** [Microsoft/Partner-Smart-Office#48]
Everything seems to work and I have set up a new environment via the Website there I have specified service address https://api.partnercenter.microsoft.com

Where is it looking for this value? Is it from the webconfiguration? Wouöd appriciate some help or guidance if possible.

2018-08-04T07:03:32  Welcome, you are now connected to log-streaming service.2018-08-04T07:03:34.276 [Information] Executing 'ProcessPartner' (Reason='This function was programmatically called via the host APIs.', Id=3b5d9cbd-cfbb-49a5-ac0a-576fdf7c048e)2018-08-04T07:03:34.278 [Error] System.Private.CoreLib: Exception while executing function: ProcessPartner. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'client'. Microsoft.Azure.WebJobs.Host: No value for named parameter 'PartnerCenterEndpoint'.2018-08-04T07:03:36.136 [Error] Executed 'ProcessPartner' (Failed, Id=3b5d9cbd-cfbb-49a5-ac0a-576fdf7c048e)2018-08-04T07:05:32  No new trace in the past 1 min(s).2018-08-04T07:06:32  No new trace in the past 2 min(s).

**Comment by isaiahwilliams** [comment]
Hi @martinliljenberg, if you are going to manually trigger this solution then you want to trigger the ProcessEnvironment function. That will read all of the entries available in the environments collection and write them to a storage queue for processing. The ProcessPartner function monitors that storage queue, and when it detects a new element in the queue it will start processing it. 

I pushed out a small bug fix this morning. I would recommend that you sync the function app with repository or redeploy the solution. This enhancement will address a change in the Microsoft Graph is returning the data for Secure Score. 

I hope this helps!

**Comment by martinliljenberg** [comment]
Hello Isaiah, Thanks you so much for your response and thanks for a great solution!. I did a new sync and got the fix . With the processenvironmentfunction do you mean the Pullenvironmentsfunction, that runs succesfully.  However the proccesspartner function still fails. Would it behave like this if anything was incorrect with the webconfig and application config or would there be any other errors? I there any other way I can check why it is failing?

**Comment by isaiahwilliams** [comment]
Hi @martinliljenberg, that is great to hear you are making some progress. Details for the customers, subscription, and utilization records is all obtained using the Partner Center API. So, it would appear that you have correctly configured the Partner Center configurations for your environment. The details for the control scores is imported using an embedded resource, so that should always be successful after the initial deployment. 

The error you are getting with respect to Secure Score can be caused by a handful of issues. I would recommend that you check the following 

- Ensure the Azure AD application that you configured in the Azure AD Application Configurations section of the portal is marked as a multi tenant application. You can verify this in the Azure management portal by click Azure Active Directory -> App Registrations -> View All Apps -> locate the app in question -> Settings -> Properties. You will want to scroll to the bottom of the properties blade, and ensure that the Multi-tenanted setting is configured to Yes
- Ensure that this Azure AD application has been granted the following permissions 
  - Windows Azure Active Directory 
    - Delegated Permissions 
      - Sign in and read user profile
  - Microsoft Graph 
    - Application Permissions
      - Read your organization security events
      - Read all usage reports
      - Read directory data
- Ensure the application has been configured for pre-consent. You can find more details about this process at https://blogs.msdn.microsoft.com/iwilliams/2017/12/01/cloud-solution-provider-pre-consent/

By chance did you use the deployment scripts included in this repository to create the Azure AD applications?

**Comment by martinliljenberg** [comment]
I changed the Azure App, and looking promising now, I will report back...

**Comment by martinliljenberg** [comment]
Hello Isaiah, Great thanks for all your help, yes I did deploy using the script. In the course of troubleshooting I did change app back and forth and now I changed back to the one deployed with the script and it works like a charm! Really exited for this and we will develop a security offering with this and other services. Great work and support, thank you!

**Comment by isaiahwilliams** [comment]
Hi @martinliljenberg! You are most welcome! I am glad that you were able to get this working. As you start to use this solution, if you have any feedback please feel free to open a new issue. I am still in the process of planning what enhancements to make with the next major release for this solution. 

Good luck with developing your new security offerings!
